drop table if exists circle_meetups, circle_stats;

CREATE TABLE circle_meetups (
    meetup_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    meetup_name TEXT NOT NULL,
    meetup_note TEXT
);

CREATE TABLE circle_stats (
    date TIMESTAMP DEFAULT now() not NULL,
    meet_id INTEGER,
    location TEXT,
    attendance INTEGER,
    notes TEXT
);


